PiaZza/Presentation/Controllers/HomeAndGardenController.cs
using BusinessLogic.Services.Interfaces;
using System.Collections.Generic;
using System.Web.Mvc;
using ViewModels.Offer;

namespace Presentation.Controllers
{
    public class HomeAndGardenController : Controller
    {
        private readonly IOfferService _offerService;
        public HomeAndGardenController(IOfferService offerService)
        {
            _offerService = offerService;
        }
        public ActionResult Index()
        {
            var allOffers = _offerService.GetOffersByCategory("Home and garden");
            var offersToView = new List<OfferListViewModel>();
            foreach (var offer in allOffers)
            {
                offersToView.Add(new OfferListViewModel
                {
                    Id = offer.Id,
                    Price = offer.Price,
                    Title = offer.Title,
                    Date = offer.Date,
                    Location = offer.Location,
                    ImageLink = _offerService.GetFirstImageLinkById(offer.Id)
                });
            }
            return View(offersToView);
        }
        public ActionResult Others()
        {
            var allOffers = _offerService.GetOffersBySubcategory("Home and garden","Others");
            var offersToView = new List<OfferListViewModel>();
            foreach (var offer in allOffers)
            {
                offersToView.Add(new OfferListViewModel
                {
                    Id = offer.Id,
                    Price = offer.Price,
                    Title = offer.Title,
                    Date = offer.Date,
                    Location = offer.Location,
                    ImageLink = _offerService.GetFirstImageLinkById(offer.Id)
                });
            }
            return View(offersToView);
        }
        public ActionResult Furniture()
        {
            var allOffers = _offerService.GetOffersBySubcategory("Home and garden", "Furniture");
            var offersToView = new List<OfferListViewModel>();
            foreach (var offer in allOffers)
            {
                offersToView.Add(new OfferListViewModel
                {
                    Id = offer.Id,
                    Price = offer.Price,
                    Title = offer.Title,
                    Date = offer.Date,
                    Location = offer.Location,
                    ImageLink = _offerService.GetFirstImageLinkById(offer.Id)
                });
            }
            return View(offersToView);
        }
        public ActionResult HomeAccessories()
        {
            var allOffers = _offerService.GetOffersBySubcategory("Home and garden", "Home accessories");
            var offersToView = new List<OfferListViewModel>();
            foreach (var offer in allOffers)
            {
                offersToView.Add(new OfferListViewModel
                {
                    Id = offer.Id,
                    Price = offer.Price,
                    Title = offer.Title,
                    Date = offer.Date,
                    Location = offer.Location,
                    ImageLink = _offerService.GetFirstImageLinkById(offer.Id)
                });
            }
            return View(offersToView);
        }
        public ActionResult GardenTools()
        {
            var allOffers = _offerService.GetOffersBySubcategory("Home and garden", "Garden tools");
            var offersToView = new List<OfferListViewModel>();
            foreach (var offer in allOffers)
            {
                offersToView.Add(new OfferListViewModel
                {
                    Id = offer.Id,
                    Price = offer.Price,
                    Title = offer.Title,
                    Date = offer.Date,
                    Location = offer.Location,
                    ImageLink = _offerService.GetFirstImageLinkById(offer.Id)
                });
            }
            return View(offersToView);
        }
    }
}

PiaZza/Presentation/Controllers/OfferController.cs
using BusinessLogic.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using ViewModels.Offer;

namespace Presentation.Controllers
{

    public class OfferController : Controller
    {
        private readonly IOfferService _offerService;
        public OfferController(IOfferService offerService)
        {
            _offerService = offerService;
        }
        public ActionResult Index()
        {
            return RedirectToAction("Index","Home");
        }
        public ActionResult ViewOffer(Nullable<Guid> Id)
        {
            try
            {
                var id = new Guid(Id.ToString());
                var offer = _offerService.GetOfferById(id);
                var account = _offerService.GetSellerByOfferId(id);
                var offerImages = new List<string>();
                foreach (var imageObject in offer.OfferImages)
                {
                    offerImages.Add(imageObject.ImageLink);
                }
                var offerDetailed = new OfferDetailsViewModel
                {
                    Id = offer.Id,
                    Title = offer.Title,
                    Description = offer.Description,
                    Location = offer.Location,
                    Price = offer.Price,
                    Date = offer.Date,
                    SellerEmail = account.Email,
                    SellerName = account.FirstName + " " + account.LastName,
                    SellerPhoneNumber = account.PhoneNumber,
                    Images = offerImages
                };
                return View(offerDetailed);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

PiaZza/Presentation/Controllers/SearchController.cs
using BusinessLogic.Services.Interfaces;
using System.Collections.Generic;
using System.Web.Mvc;
using ViewModels.Offer;

namespace Presentation.Controllers
{
    public class SearchController : Controller
    {
        private readonly IOfferService _offerService;
        public SearchController(IOfferService offerService)
        {
            _offerService = offerService;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Results(string searchString)
        {

            var offers = _offerService.GetOffersBySearchString(searchString);
            var offersToView = new List<OfferListViewModel>();
            foreach (var offer in offers)
            {
                offersToView.Add(new OfferListViewModel
                {
                    AcountId = offer.AccountId,
                    Id = offer.Id,
                    Price = offer.Price,
                    Title = offer.Title,
                    Date = offer.Date,
                    Location = offer.Location,
                    ImageLink = _offerService.GetFirstImageLinkById(offer.Id)
                });
            }
            return View(offersToView);

        }
    }
}

PiaZza/Presentation/Views/Shared/InternalServerError.cshtml
<link href="~/Content/appcontent/internal-server-error.css" rel="stylesheet" />
<div class="wrapper">
    <div class="box">
        <h1>500</h1>
        <p>Sorry, it's me, not you.</p>
        <p>&#58;&#40;</p>
        <p><a href="/">Let me try again!</a></p>
    </div>
</div>

PiaZza/Presentation/Views/Shared/NotFound.cshtml
<link href="~/Content/appcontent/page-not-found.css" rel="stylesheet" />
<div class="background">
    <div class="ground"></div>
</div>
<div class="container">
    <div class="left-section">
        <div class="inner-content">
            <h1 class="heading">404</h1>
            <p class="subheading">Looks like the page you were looking for is no longer here.</p>
        </div>
    </div>
    <div class="right-section">
        <svg class="svgimg" xmlns="http://www.w3.org/2000/svg" viewBox="51.5 -15.288 385 505.565">
            <g class="bench-legs">
                <path d="M202.778,391.666h11.111v98.611h-11.111V391.666z M370.833,390.277h11.111v100h-11.111V390.277z M183.333,456.944h11.111
          v33.333h-11.111V456.944z M393.056,456.944h11.111v33.333h-11.111V456.944z" />
            </g>
            <g class="top-bench">
                <path d="M396.527,397.917c0,1.534-1.243,2.777-2.777,2.777H190.972c-1.534,0-2.778-1.243-2.778-2.777v-8.333
          c0-1.535,1.244-2.778,2.778-2.778H393.75c1.534,0,2.777,1.243,2.777,2.778V397.917z M400.694,414.583
          c0,1.534-1.243,2.778-2.777,2.778H188.194c-1.534,0-2.778-1.244-2.778-2.778v-8.333c0-1.534,1.244-2.777,2.778-2.777h209.723
          c1.534,0,2.777,1.243,2.777,2.777V414.583z M403.473,431.25c0,1.534-1.244,2.777-2.778,2.777H184.028
          c-1.534,0-2.778-1.243-2.778-2.777v-8.333c0-1.534,1.244-2.778,2.778-2.778h216.667c1.534,0,2.778,1.244,2.778,2.778V431.25z" />
            </g>
            <g class="bottom-bench">
                <path d="M417.361,459.027c0,0.769-1.244,1.39-2.778,1.39H170.139c-1.533,0-2.777-0.621-2.777-1.39v-4.86
          c0-0.769,1.244-0.694,2.777-0.694h244.444c1.534,0,2.778-0.074,2.778,0.694V459.027z" />
                <path d="M185.417,443.75H400c0,0,18.143,9.721,17.361,10.417l-250-0.696C167.303,451.65,185.417,443.75,185.417,443.75z" />
            </g>
            <g id="lamp">
                <path class="lamp-details" d="M125.694,421.997c0,1.257-0.73,3.697-1.633,3.697H113.44c-0.903,0-1.633-2.44-1.633-3.697V84.917
          c0-1.257,0.73-2.278,1.633-2.278h10.621c0.903,0,1.633,1.02,1.633,2.278V421.997z" />
                <path class="lamp-accent" d="M128.472,93.75c0,1.534-1.244,2.778-2.778,2.778h-13.889c-1.534,0-2.778-1.244-2.778-2.778V79.861
          c0-1.534,1.244-2.778,2.778-2.778h13.889c1.534,0,2.778,1.244,2.778,2.778V93.75z" />

                <circle class="lamp-light" cx="119.676" cy="44.22" r="40.51" />
                <path class="lamp-details" d="M149.306,71.528c0,3.242-13.37,13.889-29.861,13.889S89.583,75.232,89.583,71.528c0-4.166,13.369-13.889,29.861-13.889
          S149.306,67.362,149.306,71.528z" />
                <radialGradient class="light-gradient" id="SVGID_1_" cx="119.676" cy="44.22" r="65" gradientUnits="userSpaceOnUse">
                    <stop offset="0%" style="stop-color:#FFFFFF; stop-opacity: 1" />
                    <stop offset="50%" style="stop-color:#EDEDED; stop-opacity: 0.5">
                        <animate attributeName="stop-opacity" values="0.0; 0.5; 0.0" dur="5000ms" repeatCount="indefinite"></animate>
                    </stop>
                    <stop offset="100%" style="stop-color:#EDEDED; stop-opacity: 0" />
                </radialGradient>
                <circle class="lamp-light__glow" fill="url(#SVGID_1_)" cx="119.676" cy="44.22" r="65" />
                <path class="lamp-bottom" d="M135.417,487.781c0,1.378-1.244,2.496-2.778,2.496H106.25c-1.534,0-2.778-1.118-2.778-2.496v-74.869
          c0-1.378,1.244-2.495,2.778-2.495h26.389c1.534,0,2.778,1.117,2.778,2.495V487.781z" />
            </g>
        </svg>
    </div>
</div>

PiaZza/Presentation/Views/Shared/_AddCredentialsLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/appcontent/login-clean.css" rel="stylesheet" />
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <title>@ViewBag.Title</title>
</head>
<body style="background-color:#f1f7fc;">
    <div>
        @RenderBody()
    </div>
    <script src="~/Scripts/jquery-3.5.0.min.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PiaZza/Presentation/Views/Shared/_CategoryBar.cshtml
<div class="container-fluid text-center ctg-div" style="background-color: rgba(255,139,0,1);">
    <ul class="nav justify-content-center ctg-bar">
        <li class="nav-item w-auto">
            <div class="btn-group rounded-0">
                <a class="btn btn border-0 rounded-0 btn-warning"
                   style="background-color: rgba(255,139,0,1);" href="@Url.Action("Index", "Vehicles")">
                    Vehicles
                </a>
                <button type="button" style="background-color: rgba(255,139,0,1);" class="btn btn-warning dropdown-toggle  border-0 dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu rounded" style="background-color: rgba(255,139,0,1);">
                    <a class="dropdown-item" href="@Url.Action("Cars", "Vehicles")">Cars</a>
                    <a class="dropdown-item" href="@Url.Action("Trucks", "Vehicles")">Trucks</a>
                    <a class="dropdown-item" href="@Url.Action("BigTrucks", "Vehicles")">Big trucks</a>
                    <a class="dropdown-item" href="@Url.Action("Motorcycles", "Vehicles")">Motorcycles</a>
                    <a class="dropdown-item" href="@Url.Action("Others", "Vehicles")">Others</a>
                </div>
            </div>
        </li>
        <li class="nav-item w-auto">
            <div class="btn-group rounded-0">
                <a class="btn btn border-0 rounded-0 btn-warning"
                   style="background-color: rgba(255,139,0,1);" href="@Url.Action("Index", "Electronics")">
                    Electronics
                </a>
                <button type="button" style="background-color: rgba(255,139,0,1);" class="btn btn-warning dropdown-toggle  border-0 dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu rounded" style="background-color: rgba(255,139,0,1);">
                    <a class="dropdown-item" href="@Url.Action("MobilePhones", "Electronics")">Mobile phones</a>
                    <a class="dropdown-item" href="@Url.Action("Accessories", "Electronics")">Accessories</a>
                    <a class="dropdown-item" href="@Url.Action("Computers", "Electronics")">Computers</a>
                    <a class="dropdown-item" href="@Url.Action("TV", "Electronics")">TV</a>
                    <a class="dropdown-item" href="@Url.Action("Others", "Electronics")">Others</a>
                </div>
            </div>
        </li>
        <li class="nav-item w-auto">
            <div class="btn-group rounded-0">
                <a class="btn btn border-0 rounded-0 btn-warning"
                   style="background-color: rgba(255,139,0,1);" href="@Url.Action("Index", "Estates")">
                    Estates
                </a>
                <button type="button" style="background-color: rgba(255,139,0,1);" class="btn btn-warning dropdown-toggle  border-0 dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu rounded" style="background-color: rgba(255,139,0,1);">
                    <a class="dropdown-item" href="@Url.Action("Buy", "Estates")">Buy</a>
                    <a class="dropdown-item" href="@Url.Action("Hire", "Estates")">Hire</a>
                    <a class="dropdown-item" href="@Url.Action("Rent", "Estates")">Rent</a>
                    <a class="dropdown-item" href="@Url.Action("Sell", "Estates")">Sell</a>
                    <a class="dropdown-item" href="@Url.Action("Others", "Estates")">Others</a>
                </div>
            </div>
        </li>
        <li class="nav-item w-auto">
            <div class="btn-group rounded-0">
                <a class="btn btn border-0 rounded-0 btn-warning"
                   style="background-color: rgba(255,139,0,1);" href="@Url.Action("Index", "HomeAndGarden")">
                    Home and garden
                </a>
                <button type="button" style="background-color: rgba(255,139,0,1);" class="btn btn-warning dropdown-toggle  border-0 dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu rounded" style="background-color: rgba(255,139,0,1);">

                    <a class="dropdown-item" href="@Url.Action("Furniture", "HomeAndGarden")">Furniture</a>
                    <a class="dropdown-item" href="@Url.Action("HomeAccessories", "HomeAndGarden")">Home accessories</a>
                    <a class="dropdown-item" href="@Url.Action("GardenTools", "HomeAndGarden")">Garden tools</a>
                    <a class="dropdown-item" href="@Url.Action("Others", "HomeAndGarden")">Others</a>
                </div>
            </div>
        </li>
        <li class="nav-item w-auto">
            <div class="btn-group rounded-0">
                <a class="btn btn border-0 rounded-0 btn-warning"
                   style="background-color: rgba(255,139,0,1);" href="@Url.Action("Index", "Pets")">
                    Pets
                </a>
                <button type="button" style="background-color: rgba(255,139,0,1);" class="btn btn-warning dropdown-toggle  border-0 dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu rounded" style="background-color: rgba(255,139,0,1);">
                    <a class="dropdown-item" href="@Url.Action("Pets", "Pets")">Pets</a>
                    <a class="dropdown-item" href="@Url.Action("Food", "Pets")">Pet food</a>
                    <a class="dropdown-item" href="@Url.Action("Others", "Pets")">Others</a>
                </div>
            </div>
        </li>
    </ul>
</div>

PiaZza/Presentation/Views/Shared/_Footer.cshtml
<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li class="mt-1 mb-2">
                            Made within the FiiPractic project.
                        </li>
                        <li class="mt-1 mb-2">
                            .NET Framework Section.
                        </li>
                        <li class="mt-1 mb-2">
                            Supported by BeeNear.
                        </li>
                    </ul>

                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3></h3>
                    <ul>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3></h3>
                    <ul>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
            </div>
            <p class="copyright">Iurea Bogdan Iulian © 2020</p>
        </div>
    </footer>
</div>

PiaZza/Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Fonts/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/appcontent/Navigation.css" rel="stylesheet" />
    <link href="~/Content/appcontent/Footer-Dark.css" rel="stylesheet" />
    <link href="~/Content/appcontent/styles.css" rel="stylesheet" />
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    @RenderSection("styles", required: false);
    <title>@ViewBag.Title</title>
</head>
<body style="background-color:#f1f7fc;">
    @{
        Html.RenderPartial("_NavBar");
    }
    <div class="container-fluid m-0 p-0 mt-5" style="min-height: 800px;">
        @RenderBody()
    </div>
    @{ Html.RenderPartial("_Footer"); }
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/appscripts/navbar.js"></script>
    @RenderSection("scripts", required: false)
</body>

</html>

PiaZza/Presentation/Views/Shared/_NavBar.cshtml
@if (Session["UserId"] == null)
{
    <div>
        <nav class="navbar navbar-light navbar-expand-md navigation-clean-button fixed-top" id="mynavbar" style="background-color: rgba(255,139,0,1);">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">PiaZza</a>
                <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
                    <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    @using (Html.BeginForm("Results", "Search", FormMethod.Get,new { @class="w-100"})) {
                        <div class="input-group" id="searchDiv">
                            <input type="text" class="form-control" name="searchString" placeholder="Search" aria-label="Search" aria-describedby="basic-addon1" id="searchString">
                        </div>
                    }
                    <ul class="nav navbar-nav mr-auto">
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle nav-link text-dark" style="background-color: rgba(255,139,0,1);" data-toggle="dropdown" aria-expanded="false" href="#">MyAccount</a>
                            <div class="dropdown-menu rounded"  role="menu" style="background-color: rgba(255,139,0,1);">
                                <a class="dropdown-item" role="presentation" href="@Url.Action("Login", "Account")">Log In</a>
                                <a class="dropdown-item" role="presentation" href="@Url.Action("CreateAccount", "Account")">Register</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
}
else
{
    <div>
        <nav class="navbar navbar-light navbar-expand-md navigation-clean-button fixed-top" id="mynavbar" style="background-color: rgba(255,139,0,1);">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">PiaZza</a>
                <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
                    <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"> </span>
                </button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    @using (Html.BeginForm("Results", "Search", FormMethod.Get,new { @class="w-100"})) {
                        <div class="input-group" id="searchDiv">
                            <input type="text" class="form-control" name="searchString" placeholder="Search" aria-label="Search" aria-describedby="basic-addon1" id="searchString">
                        </div>
                    }
                    <ul class="nav navbar-nav mr-auto">
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle nav-link text-dark" data-toggle="dropdown" aria-expanded="false" href="#">@Session["UserName"]</a>
                            <div class="dropdown-menu rounded" role="menu" style="background-color: rgba(255,139,0,1);">
                                <a class="dropdown-item" role="presentation" href="@Url.Action("MyAccount","Account")">My Account</a>
                                <a class="dropdown-item" role="presentation" href="@Url.Action("MyOffers","Account")">My Offers</a>
                                <a class="dropdown-item" role="presentation" href="@Url.Action("AddNewOffer","Account")">Add new Offer</a>
                                <a class="dropdown-item" role="presentation" href="@Url.Action("LogOut","Account")">Log Out</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
}

PiaZza/Presentation/Views/Shared/_OffersLayout.cshtml
@model IEnumerable<ViewModels.Offer.OfferListViewModel>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Fonts/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/appcontent/Navigation.css" rel="stylesheet" />
    <link href="~/Content/appcontent/Footer-Dark.css" rel="stylesheet" />
    <link href="~/Content/appcontent/styles.css" rel="stylesheet" />
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <link href="~/Content/appcontent/category-bar.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body class="m-0 p-0" style="background-color:#f1f7fc;">
    @{Html.RenderPartial("_NavBar");}
    @{Html.RenderPartial("_CategoryBar"); }
    <div class="container" style="min-height: 800px;">
        @RenderBody()
        <div class="album py-5">
            <div class="container h-auto mt-5">
                <div class="row">
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <div class="col-md-4">
                                <div class="card mb-4 shadow-sm">
                                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
                                        <rect width="100%" height="100%" fill="#55595c"></rect>
                                        <title>@Html.DisplayFor(modelItem => item.Title)</title>
                                        <image width="100%" height="100%" xlink:href="@Html.DisplayFor(modelItem => item.ImageLink)"></image>
                                    </svg>
                                    <div class="card-body h-200">
                                        <p class="card-text">@Html.DisplayFor(modelItem => item.Title)</p>
                                        <div class="d-flex justify-content-between align-items-center ml-0 w-100">
                                            <a href="@Url.Action("ViewOffer","Offer",new {id=item.Id})" style="background-color: rgba(255,139,0,1);" class="btn w-100" role="button">@Html.DisplayFor(model => item.Price)$</a>
                                        </div>
                                        <small class="text-muted w-100">@Html.DisplayFor(model => item.Location)</small><br />
                                        <small class="text-muted w-100">@Html.DisplayFor(model => item.Date.Year)</small>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
        <div class="container mb-3">
        </div>
    </div>
    @{ Html.RenderPartial("_Footer"); }
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/appscripts/navbar.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>